apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-caas
  annotations:
    meta.crossplane.io/maintainer: The configuration-caas Configuration
    meta.crossplane.io/source: github.com/upbound/configuration-caas
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration-caas configuration offers Kubernetes Clusters.
    meta.crossplane.io/readme: |
      This Configuration bundles an Upbound Cloud extension and an API
      definition. The API will allow control planes to provision fully
      configured Kubernetes Service clusters, composed
      using cloud service primitives from the Upbound Official Providers
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/platform-ref-aws
      # renovate: datasource=github-releases depName=upbound/platform-ref-aws
      version: "v0.9.0"
    - configuration: xpkg.upbound.io/upbound/platform-ref-gcp
      # renovate: datasource=github-releases depName=upbound/platform-ref-gcp
      version: "v0.5.0"
    - configuration: xpkg.upbound.io/upbound/platform-ref-azure
      # renovate: datasource=github-releases depName=upbound/platform-ref-azure
      version: "v0.8.0"
    - provider: xpkg.upbound.io/upbound/provider-upbound
      # renovate: datasource=github-releases depName=upbound/provider-upbound
      version: "v0.7.0"
