apiVersion: caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: caas-gcp-argocd
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    cloud: gcp
    id: caas-gcp-argocd
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: n1-standard-4
    gitops:
      operator: argocd
      git:
        url: https://github.com/upbound/configuration-caas.git
        path: configuration/infrastructure.yaml
        ref:
          name: HEAD
  writeConnectionSecretToRef:
    name: caas-gcp-argocd-kubeconfig
