apiVersion: mcp.caas.upbound.io/v1alpha1
kind: Connector
metadata:
  name: caas-aws-flux
  namespace: default
spec:
  parameters:
    organizationName: upbound
    controlPlaneName: caas
    version: "0.3.5"
    providerConfigName: caas-aws-flux
