apiVersion: azure.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: spoke-azure-cluster
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: spoke-azure-cluster
    region: westus
    version: "1.27.3"
    nodes:
      count: 1
      instanceType: Standard_B2s
    gitops:
      git:
        url: https://github.com/upbound/configuration-caas/
        ref:
          # refs/heads/main
          # refs/tags/v0.1.0
          # refs/pull/420/head
          # refs/merge-requests/1/head
          name: refs/heads/main
  writeConnectionSecretToRef:
    name: spoke-azure-cluster-kubeconfig
