apiVersion: gcp.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: spoke-gcp-cluster
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: spoke-gcp-cluster
    region: us-west2
    version: latest
    nodes:
      count: 3
      instanceType: n1-standard-4
    gitops:
      git:
        url: https://github.com/upbound/configuration-caas/
        ref:
          # refs/heads/main
          # refs/tags/v0.1.0
          # refs/pull/420/head
          # refs/merge-requests/1/head
          name: refs/heads/main
  writeConnectionSecretToRef:
    name: spoke-gcp-cluster-kubeconfig